"""Primera migracion

Revision ID: 273077170d5b
Revises: 1db13882d216
Create Date: 2025-07-17 10:27:50.758150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273077170d5b'
down_revision: Union[str, Sequence[str], None] = '1db13882d216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('latitud_docente', sa.Float(), nullable=False),
    sa.Column('longitud_docente', sa.Float(), nullable=False),
    sa.Column('direccion_referencia', sa.String(length=500), nullable=True),
    sa.Column('radio_permitido_metros', sa.Integer(), nullable=True),
    sa.Column('permite_asistencia_tardia', sa.Boolean(), nullable=True),
    sa.Column('minutos_tolerancia', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_asistencia_id'), 'sesiones_asistencia', ['id'], unique=False)
    op.create_table('asistencias_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('fecha_marcado', sa.DateTime(), nullable=True),
    sa.Column('latitud_estudiante', sa.Float(), nullable=True),
    sa.Column('longitud_estudiante', sa.Float(), nullable=True),
    sa.Column('distancia_metros', sa.Float(), nullable=True),
    sa.Column('metodo_marcado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('es_tardanza', sa.Boolean(), nullable=True),
    sa.Column('justificado', sa.Boolean(), nullable=True),
    sa.Column('motivo_justificacion', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_asistencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_estudiantes_id'), 'asistencias_estudiantes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencias_estudiantes_id'), table_name='asistencias_estudiantes')
    op.drop_table('asistencias_estudiantes')
    op.drop_index(op.f('ix_sesiones_asistencia_id'), table_name='sesiones_asistencia')
    op.drop_table('sesiones_asistencia')
    # ### end Alembic commands ###
