"""Primera migracion

Revision ID: 6e2c13ccb4ec
Revises: e8827e5d5c01
Create Date: 2025-07-19 09:44:05.498159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2c13ccb4ec'
down_revision: Union[str, Sequence[str], None] = 'e8827e5d5c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificaciones', sa.Column('para_estudiante', sa.Boolean(), nullable=True))
    op.alter_column('notificaciones', 'padre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificaciones', 'padre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notificaciones', 'para_estudiante')
    # ### end Alembic commands ###
